name: Automatically Approve / Merge PR
on:
  pull_request:

jobs:
  Auto_Approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: github.actor == 'jim60105'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  Auto_Merge_PR:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    needs: "Auto_Approve"
    steps:
      - name: Git Auto Merge
        uses: plm9606/automerge_actions@1.2.2
        with:
          # Use PAT to trigger another workflow
          github-token: ${{ secrets.CR_PAT }}
          merge-method: squash
          reviewers-number: 0
          label-name: "automerge"
          auto-delete: true

      - name: Remove label
        if: ${{ success() }}
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: "automerge"
          type: remove
